import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from '../components/navbar'
import Footer from '../components/footer'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main className={styles.main}>
				<div id="hero" className = {styles.hero}>
					<div className={styles.banner}>
						<span className={styles.hookspan}>We weave <span className={styles.hookbold}>websites!</span></span>
						<div id="caption">
							<span className={styles.hookspan}>Try saying that ten times <span className={styles.hookbold}>fast.</span></span>
						</div>
						<button/>
					</div>

					<div id="banner2">
						<div id="image2"></div>
						<div id="caption"></div>
					</div>	

				</div>

				<div id="secondpart">
					
				</div>
			</main>

			<Footer />

		</div>
	)
}
